name: bootpay_flutter
description: This plugin is payment modules of Bootpay for Flutter version.
version: 0.0.9
author: Jace Shim <jaceshim76@gmail.com>
homepage: https://github.com/jaceshim/bootpay_flutter

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: jaceshim.bootpay_flutter
    pluginClass: BootpayFlutterPlugin
